apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-deployement
spec:
  replicas: 2
  selector:
    matchLabels:
      name: jokes-api
  template:
    metadata:
      labels: 
        name: jokes-api
    spec:
      containers:
        - name: jokes-api-con
          image: suyashagrahari2121/jokes-api
          ports: 
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-cluser-ip-serv/jokesdb" 
          envFrom:
            - configMapRef:
                name:  jokes-api-config 
    
  
